name: keras
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - pandas
  - matplotlib
  - keras
  - tensorflow
  - scikit-learn
  - cython
  - jupyter
  - nb_conda_kernels
  - pip:
    - lime
